// using this, as the browser load only the required files , not whole db/shared/schemas/ files.
export * from '../shared/schemas/objects/AppointmentUncheckedCreateInput.schema';
export * from '../shared/schemas/objects/PatientUncheckedCreateInput.schema';
export * from '../shared/schemas/objects/UserUncheckedCreateInput.schema';
export * from '../shared/schemas/objects/StaffUncheckedCreateInput.schema'
export * from '../shared/schemas/objects/ClaimUncheckedCreateInput.schema'
export * from '../shared/schemas/objects/InsuranceCredentialUncheckedCreateInput.schema'
export * from '../shared/schemas/objects/PdfFileUncheckedCreateInput.schema'
export * from '../shared/schemas/objects/PdfGroupUncheckedCreateInput.schema'
export * from '../shared/schemas/enums/ClaimStatus.schema'
export * from '../shared/schemas/objects/PaymentUncheckedCreateInput.schema'
export * from '../shared/schemas/objects/ServiceLineTransactionCreateInput.schema'
export * from '../shared/schemas/enums/PaymentMethod.schema'
export * from '../shared/schemas/enums/PaymentStatus.schema'
export * from '../shared/schemas/enums/NotificationTypes.schema'
export * from '../shared/schemas/objects/NotificationUncheckedCreateInput.schema'
export * from '../shared/schemas/objects/DatabaseBackupUncheckedCreateInput.schema'
export * from '../shared/schemas/objects/CloudFolderUncheckedCreateInput.schema'
export * from '../shared/schemas/objects/CloudFileUncheckedCreateInput.schema'